spring.application.name=MongoBanque.jpa

#Database
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=mongobank

#Jpa-Hibernate
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDB53Dialect